### ISSUE TITLE
SPEEDHACK32.dll

### ISSUE THREAD

**Issue by skerit** [absolute-gamer/Speedhack#1]
I would guess the DLL in the bin folder is a compilation of the example in the src folder?

I'm injecting the DLL into a game, but it doesn't seem to take. Is detours also needed as a runtime package or something?

**Comment by absolute-gamer** [comment]
It's a compilation of an old example, compile it yourself w/ the detours library here: https://www.microsoft.com/en-us/download/details.aspx?id=52586
